import crypto from "node:crypto";
import zlib from "node:zlib";
import { promisify } from "node:util";
import ws from "../../gateway/node_modules/ws/index.js";
const { WebSocketServer } = ws;
import { createStore } from "../../src/core/file-store.js";
import { chinaNow } from "../../src/core/time.js";
import { renderDashboard } from "../../src/frontend/dashboard.js";

const gunzip = promisify(zlib.gunzip), inflate = promisify(zlib.inflate), brotliDecompress = promisify(zlib.brotliDecompress);
const developmentToken = "dev-vitalmesh-token";
const sensorLabels = { battery_level:"电池电量",battery_state:"电池状态",storage:"存储空间",connectivity_ssid:"Wi-Fi 名称",connectivity_bssid:"Wi-Fi 地址",connectivity_connection_type:"网络连接类型",connectivity_sim_1:"SIM 卡 1",connectivity_sim_2:"SIM 卡 2",last_update_trigger:"最后更新触发方式","app-version":"App 版本","location-permission":"位置权限","iphone-audio-output":"音频输出设备",kioskMode:"展示模式",kioskBrightness:"屏幕亮度",kioskVolume:"音量",kioskScreensaver:"屏幕保护",cameraMotion:"摄像头动作检测",cameraStream:"摄像头视频流",geocoded_location:"地理编码位置",activity:"当前活动状态",focus:"专注模式",pressure:"气压",health_steps:"健康步数",health_distance_walking_running:"步行/跑步距离",health_active_energy_burned:"活动能量消耗",health_basal_energy_burned:"基础能量消耗",health_flights_climbed:"爬升楼层数",health_apple_exercise_time:"锻炼时间",health_dietary_water:"饮水量",health_vo2_max:"最大摄氧量",health_body_mass:"体重",health_body_fat_percentage:"体脂率",health_lean_body_mass:"瘦体重",health_height:"身高",health_heart_rate:"心率",health_resting_heart_rate:"静息心率",health_walking_heart_rate_average:"步行平均心率",health_heart_rate_variability:"心率变异性",health_blood_pressure_systolic:"收缩压",health_blood_pressure_diastolic:"舒张压",health_respiratory_rate:"呼吸频率",health_oxygen_saturation:"血氧饱和度",health_body_temperature:"体温",health_basal_body_temperature:"基础体温",health_blood_glucose:"血糖",pedometer_distance:"计步器距离",pedometer_floors_ascended:"上行楼层数",pedometer_floors_descended:"下行楼层数",pedometer_steps:"计步器步数",pedometer_avg_active_pace:"平均活动配速" };
const json = (res, status, body) => (res.writeHead(status, { "content-type":"application/json; charset=utf-8" }), res.end(JSON.stringify(body)));
const html = (res, status, body) => (res.writeHead(status, { "content-type":"text/html; charset=utf-8", "cache-control":"no-store, no-cache, must-revalidate" }), res.end(body));
const redirect = (res, location) => (res.writeHead(302, { location, "cache-control":"no-store, no-cache, must-revalidate" }), res.end());
const escapeHtml = (value) => String(value ?? "").replace(/[&<>\"']/g, (character) => ({ "&":"&amp;", "<":"&lt;", ">":"&gt;", "\"":"&quot;", "'":"&#39;" })[character]);
const readBody = async (req) => { const chunks=[]; for await (const chunk of req) chunks.push(chunk); let body=Buffer.concat(chunks); const enc=(req.headers["content-encoding"]??"").toLowerCase(); if(enc==="gzip")body=await gunzip(body); else if(enc==="deflate")body=await inflate(body); else if(enc==="br")body=await brotliDecompress(body); const raw=body.toString("utf8"); if(!raw)return {}; if((req.headers["content-type"]??"").includes("application/x-www-form-urlencoded"))return Object.fromEntries(new URLSearchParams(raw)); try{return JSON.parse(raw)}catch(error){error.rawBody=raw;throw error} };
const entityId = (item) => String(item.sensor_id).replace(/[^a-zA-Z0-9_]+/g, "_").toLowerCase();
const states = (store) => store.listSensors().map((item) => { const domain=item.type==="binary_sensor"?"binary_sensor":"sensor"; const id=`${domain}.${entityId(item)}`; return {entity_id:id,state:String(item.latest.state??"null"),attributes:{...item.latest.attributes,device_id:item.device_id,source_unique_id:item.unique_id},last_changed:item.last_received,last_updated:item.last_received,context:{}}; });
const compressedStates = (store) => Object.fromEntries(states(store).map((s)=>[s.entity_id,{s:s.state,a:s.attributes,c:s.context,lc:Date.parse(s.last_changed)/1000}]));
const haConfig = () => ({ latitude: 0, longitude: 0, elevation: 0, unit_system: { length: "km", mass: "kg", temperature: "\u00b0C", volume: "L", pressure: "hPa", wind_speed: "m/s", accumulated_precipitation: "mm" }, location_name: "VitalMesh", time_zone: "Asia/Shanghai", components: ["mobile_app", "webhook"], version: "ha-compat-0.1.0", cloudhook_url: null, remote_ui_url: null, hass_device_id: null });

export const createHomeAssistantPlatform = ({ dbFile, rawLogFile, token }) => {
  const store=createStore(dbFile, rawLogFile, sensorLabels); const registrations=new Map(); const authorizationCodes=new Map(); const wss=new WebSocketServer({noServer:true});
  const authenticated=(req)=>token===""||req.headers.authorization===`Bearer ${token}`;
  const dataForDashboard=()=>{ const messages=store.listMessages(); const counts={}; for(const m of messages){const t=m.payload?.type??"(无 type)";counts[t]=(counts[t]??0)+1} return {total_messages:messages.length,message_counts:counts,devices:store.listDevices(),sensors:store.listSensors()}; };
  const authorizationRedirect = (url) => {
    const redirectUri = url.searchParams.get("redirect_uri");
    if (!redirectUri) return { error: "Missing redirect_uri" };
    const code = crypto.randomBytes(24).toString("hex");
    authorizationCodes.set(code, { clientId:url.searchParams.get("client_id"), redirectUri, createdAt:Date.now() });
    const callback = new URL(redirectUri);
    callback.searchParams.set("code", code);
    if (url.searchParams.get("state")) callback.searchParams.set("state", url.searchParams.get("state"));
    const target = callback.toString();
    console.log(JSON.stringify({type:"oauth",event:"authorization_code_issued",client_id:url.searchParams.get("client_id"),redirect_uri:redirectUri}));
    return { target };
  };
  const loginPage = (url, error = "") => {
    const fields = [...url.searchParams.entries()]
      .filter(([key]) => key !== "token")
      .map(([key, value]) => `<input type="hidden" name="${escapeHtml(key)}" value="${escapeHtml(value)}">`)
      .join("");
    const message = error ? `<p style="color:#d32f2f">${escapeHtml(error)}</p>` : "";
    return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VitalMesh 登录</title><style>body{margin:0;background:#101419;color:#e8edf2;font:16px -apple-system,BlinkMacSystemFont,sans-serif;padding:24px}main{max-width:480px;margin:10vh auto;background:#171e25;border-radius:12px;padding:24px;box-sizing:border-box}label{display:block;color:#9eabb5;margin:18px 0 8px}input{width:100%;box-sizing:border-box;padding:12px;border:1px solid #53636d;border-radius:8px;background:#101419;color:#fff;font-size:16px}button{margin-top:20px;padding:11px 18px;border:0;border-radius:8px;background:#03a9f4;color:#fff;font-size:16px;cursor:pointer}</style></head><body><main><h1>VitalMesh 登录</h1><p>请输入 HA Token 继续连接 Home Assistant。</p>${message}<form method="post" action="/login">${fields}<label for="token">Token</label><input id="token" name="token" type="password" autocomplete="current-password" required autofocus><button type="submit">登录</button></form></main></body></html>`;
  };
  const handleWebhook=async(req,id)=>{let payload;try{payload=await readBody(req)}catch(error){payload={_invalid_json:true,raw_body:error.rawBody??null}}; const receivedAt=chinaNow(); console.log(JSON.stringify({type:"webhook_debug",webhook_id:id,payload_type:payload?.type??null,data_type:Array.isArray(payload?.data)?"array":typeof payload?.data,encrypted:payload?.encrypted===true,keys:payload&&typeof payload==="object"?Object.keys(payload):[]})); store.recordMessage(id,payload,receivedAt); const registration=registrations.get(id) ?? store.getRegistration(id); const deviceId=registration?.device_id ?? (id ? `ha-webhook:${id}` : "unknown-device"); const sensors=Array.isArray(payload?.data)?payload.data:(payload?.data?.unique_id?[payload.data]:[]); for(const sensor of sensors){if(sensor?.unique_id)store.upsertSensor(sensor,deviceId,receivedAt)} let body={}; if(payload?.type==="get_config")body=haConfig(); else if(payload?.type==="get_zones")body=[]; return {status:200,body};};
  const handleHttp=async(req,url)=>{
    if(req.method==="GET"&&url.pathname==="/")return(res)=>html(res,200,renderDashboard(dataForDashboard()));
    if(req.method==="GET"&&url.pathname==="/api/config")return(res)=>json(res,200,{location_name:"VitalMesh",version:"ha-compat-0.1.0",state:"RUNNING",components:["mobile_app","webhook"],time_zone:"UTC",safe_mode:false,recovery_mode:false});
    if(req.method==="GET"&&url.pathname==="/auth/providers")return(res)=>json(res,200,{providers:[{type:"homeassistant",name:"Home Assistant",id:"homeassistant"}]});
    if(req.method==="GET"&&url.pathname==="/.well-known/oauth-authorization-server")return(res)=>json(res,200,{issuer:`${url.origin}/`,authorization_endpoint:`${url.origin}/auth/authorize`,token_endpoint:`${url.origin}/auth/token`,response_types_supported:["code"],grant_types_supported:["authorization_code","refresh_token"],code_challenge_methods_supported:["plain","S256"],token_endpoint_auth_methods_supported:["none"]});
    if(req.method==="GET"&&url.pathname==="/api/health")return(res)=>json(res,200,{ok:true,service:"vitalmesh-ha-compat-gateway"});
    if(req.method==="GET"&&url.pathname==="/api/discovery_info")return(res)=>json(res,200,{base_url:url.origin,location_name:"VitalMesh",requires_api_password:false,version:"ha-compat-0.1.0"});
    if(req.method==="GET"&&url.pathname==="/favicon.ico")return(res)=>(res.writeHead(204),res.end());
    if(req.method==="GET"&&url.pathname==="/api/vitalmesh/dashboard"){if(!authenticated(req))return(res)=>json(res,401,{message:"Invalid authentication"});return(res)=>json(res,200,dataForDashboard())}
    if(req.method==="GET"&&url.pathname==="/api/vitalmesh/records"){if(!authenticated(req))return(res)=>json(res,401,{message:"Invalid authentication"});const records=store.listMessages();return(res)=>json(res,200,{records:records.reverse(),total:records.length})}
    if(req.method==="GET"&&url.pathname.startsWith("/api/vitalmesh/sensors/")&&url.pathname.endsWith("/history")){if(!authenticated(req))return(res)=>json(res,401,{message:"Invalid authentication"});const sensorId=decodeURIComponent(url.pathname.slice("/api/vitalmesh/sensors/".length,-"/history".length));return(res)=>json(res,200,{sensor_id:sensorId,history:store.history(sensorId)})}
    if(req.method==="GET"&&url.pathname==="/api/states"){if(!authenticated(req))return(res)=>json(res,401,{message:"Invalid authentication"});return(res)=>json(res,200,states(store))}
    if(req.method==="GET"&&(url.pathname==="/api/services"||url.pathname==="/api/panels"))return(res)=>json(res,200,url.pathname.endsWith("services")?[]:{});
    if(req.method==="GET"&&url.pathname==="/api/ios/config")return(res)=>json(res,200,{push:{categories:[]}});
    if(req.method==="GET"&&url.pathname==="/login"){return(res)=>html(res,200,loginPage(url))}
    if(req.method==="POST"&&url.pathname==="/login"){
      const body=await readBody(req); const requested=new URL(url.origin+"/login");
      for(const [key,value] of Object.entries(body)) if(key!=="token"&&typeof value==="string") requested.searchParams.set(key,value);
      if(token!==""&&body.token!==token)return(res)=>html(res,401,loginPage(requested,"Token 错误，请重试。"));
      const result=authorizationRedirect(requested); if(result.error)return(res)=>json(res,400,{message:result.error});
      return(res)=>redirect(res,result.target);
    }
    if(req.method==="GET"&&url.pathname==="/auth/authorize"){if(!url.searchParams.get("redirect_uri"))return(res)=>json(res,400,{message:"Missing redirect_uri"});if(token!==""){const loginUrl=new URL("/login",url.origin);for(const [key,value] of url.searchParams)loginUrl.searchParams.append(key,value);return(res)=>redirect(res,loginUrl.toString())}const result=authorizationRedirect(url);return(res)=>html(res,200,`<!doctype html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>VitalMesh authorization</title><p>授权成功，正在返回 Home Assistant App…</p><a id="continue" href="${escapeHtml(result.target)}">返回 App</a><script>window.location.href=${JSON.stringify(result.target).replace(/</g,"\\u003c")}</script>`) }
    if(req.method==="POST"&&url.pathname==="/auth/token"){const body=await readBody(req);const code=typeof body.code==="string"?body.code:null;const clientId=typeof body.client_id==="string"?body.client_id:null;const grantType=typeof body.grant_type==="string"?body.grant_type:null;console.log(JSON.stringify({type:"oauth",event:"token_request",grant_type:grantType,client_id:clientId,has_code:Boolean(code),has_refresh_token:Boolean(body.refresh_token)}));if(grantType==="authorization_code"&&code&&authorizationCodes.has(code))authorizationCodes.delete(code);const issued=token||developmentToken;return(res)=>json(res,200,{access_token:issued,refresh_token:issued,token_type:"Bearer",expires_in:31536000})}
    if(req.method==="POST"&&url.pathname==="/api/mobile_app/registrations"){if(!authenticated(req))return(res)=>json(res,401,{message:"Invalid authentication"});const payload=await readBody(req);console.log(JSON.stringify({type:"mobile_app",event:"registration_request",fields:Object.keys(payload??{}),device_id:payload?.device_id??null,device_name:payload?.device_name??null,app_id:payload?.app_id??null}));const required=["app_id","app_name","app_version","device_name","manufacturer","model","os_name"];const missing=required.filter(k=>typeof payload[k]!=="string");if(missing.length)return(res)=>json(res,400,{message:`Missing fields: ${missing.join(", ")}`});const deviceId=payload.device_id??crypto.randomUUID();const existing=store.getRegistrationByDeviceId(deviceId);const registration={...payload,device_id:deviceId,webhook_id:existing?.webhook_id??crypto.randomBytes(16).toString("hex"),created_at:existing?.created_at??chinaNow()};registrations.set(registration.webhook_id,registration);store.register(registration);return(res)=>json(res,201,{cloudhook_url:null,remote_ui_url:null,secret:null,webhook_id:registration.webhook_id})}
    const match=url.pathname.match(/^\/api\/webhook(?:\/([^/]*))?\/?$/); if(req.method==="POST"&&match){const result=await handleWebhook(req,match[1]||null);return(res)=>json(res,result.status,result.body)}
    return null;
  };
  const attachWebSocket=(server)=>{server.on("upgrade",(req,socket,head)=>{const url=new URL(req.url,`http://${req.headers.host??"localhost"}`);if(url.pathname!=="/api/websocket"){socket.destroy();return}wss.handleUpgrade(req,socket,head,(ws)=>{const cid=crypto.randomBytes(6).toString("hex");let auth=false;console.log(JSON.stringify({type:"websocket",event:"connected",connection_id:cid}));ws.send(JSON.stringify({type:"auth_required",ha_version:"ha-compat-0.1.0"}));ws.on("message",(message)=>{let r;try{r=JSON.parse(message)}catch{return}console.log(JSON.stringify({type:"websocket_message",connection_id:cid,request_type:r.type,request_id:r.id??null}));if(r.type==="auth"){if(token!==""&&r.access_token!==token&&r.access_token!==developmentToken)return ws.close(1008,"invalid access token");auth=true;return ws.send(JSON.stringify({type:"auth_ok",ha_version:"ha-compat-0.1.0"}))}if(!auth){return ws.close(1008,"authentication required")}if(r.id===undefined)return;if(r.type==="ping")return ws.send(JSON.stringify({id:r.id,type:"pong"}));let result=null;if(r.type==="get_config")result=haConfig();else if(r.type==="auth/current_user")result={id:"vitalmesh",name:"VitalMesh",is_owner:true,is_admin:true};else if(r.type==="get_panels")result={};else if(String(r.type??"").startsWith("config/"))result=[];ws.send(JSON.stringify({id:r.id,type:"result",success:true,result}));if(r.type==="subscribe_entities")ws.send(JSON.stringify({id:r.id,type:"event",event:{a:compressedStates(store)}}))});ws.on("close",()=>console.log(JSON.stringify({type:"websocket",event:"closed",connection_id:cid})))})})};
  return { handleHttp, attachWebSocket, store, close:()=>{wss.close();store.close()} };
};
